id: ID894805D
legacy_id: P010335
ocr_import_info:
  bdrc_scan_id: W4CZ24513
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T18:12:33'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T18:27:08.760231+00:00'
last_modified: 2022-09-04 02:27:12.815601
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ24513
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW4CZ24513
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཨང་ཡིག་བདུན་ཅུ་མ།
  author: ཁ་རག་སྒོམ་ཆུང་དབང་ཕྱུག་བློ་གྲོས།
statistics:
  ocr_word_mean_confidence_index: 0.8657409229565188
  ocr_word_median_confidence_index: 0.9399999976158142
quality: null
bases:
  I1KG14696:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG14696
      total_pages: 20
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG14696.txt
    statistics:
      ocr_word_median_confidence_index: 0.9399999976158142
      ocr_word_mean_confidence_index: 0.8657409229565188
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
