id: ID894805D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T18:12:43+00:00'
last_modified: '2022-06-08T12:50:04.412356+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ24513
  title: ཨང་ཡིག་བདུན་ཅུ་མ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F8B4:
      image_group_id: I1KG14696
      title: ''
      total_pages: 20
      order: 1
      base_file: F8B4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
