id: P010335
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-19 20:44:38.228329
source_metadata:
  id: bdr:W4CZ24513
  title: ཨང་ཡིག་བདུན་ཅུ་མ།
  author: ''
  volumes:
    d0503ff1fd714769bdc6870bc1355383:
      image_group_id: I1KG14696
      title: ''
      volume_number: 1
      total_pages: 20
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
